export interface StickerEntry {
  code: string;
  name: string;
}

export interface CategoryEntry {
  name: string;
  stickers: StickerEntry[];
}

export const COPA2026_ALBUM_SLUG = "copa-mundo-2026";

export const COPA2026_CATEGORIES: CategoryEntry[] = [
  {
    name: "We Are Panini",
    stickers: [{ code: "00", name: "Panini Logo" }],
  },
  {
    name: "FIFA World Cup 2026",
    stickers: [
      { code: "FWC-1", name: "Official Emblem 1/2" },
      { code: "FWC-2", name: "Official Emblem 2/2" },
      { code: "FWC-3", name: "Official Mascots" },
      { code: "FWC-4", name: "Official Slogan" },
      { code: "FWC-5", name: "Official Ball" },
    ],
  },
  {
    name: "Host Countries",
    stickers: [
      { code: "FWC-6", name: "Canada (Host Country Emblem)" },
      { code: "FWC-7", name: "Mexico (Host Country Emblem)" },
      { code: "FWC-8", name: "USA (Host Country Emblem)" },
    ],
  },
  {
    name: "Algeria",
    stickers: [
      { code: "ALG-1", name: "Emblem" },
      { code: "ALG-2", name: "Alexis Guendouz" },
      { code: "ALG-3", name: "Ramy Bensebaini" },
      { code: "ALG-4", name: "Youcef Atal" },
      { code: "ALG-5", name: "Rayan Aït-Nouri" },
      { code: "ALG-6", name: "Mohamed Amine Tougai" },
      { code: "ALG-7", name: "Aïssa Mandi" },
      { code: "ALG-8", name: "Ismael Bennacer" },
      { code: "ALG-9", name: "Houssem Aquar" },
      { code: "ALG-10", name: "Hicham Boudaoui" },
      { code: "ALG-11", name: "Ramiz Zerrouki" },
      { code: "ALG-12", name: "Nabil Bentalab" },
      { code: "ALG-13", name: "Team Photo" },
      { code: "ALG-14", name: "Farés Chaibi" },
      { code: "ALG-15", name: "Riyad Mahrez" },
      { code: "ALG-16", name: "Said Benrhama" },
      { code: "ALG-17", name: "Anis Hadj Moussa" },
      { code: "ALG-18", name: "Amine Gouiri" },
      { code: "ALG-19", name: "Baghdad Bounedjah" },
      { code: "ALG-20", name: "Mohammed Amoura" },
    ],
  },
  {
    name: "Argentina",
    stickers: [
      { code: "ARG-1", name: "Emblem" },
      { code: "ARG-2", name: "Emiliano Martinez" },
      { code: "ARG-3", name: "Nahuel Molina" },
      { code: "ARG-4", name: "Cristian Romero" },
      { code: "ARG-5", name: "Nicolas Otamendi" },
      { code: "ARG-6", name: "Nicolas Tagliafico" },
      { code: "ARG-7", name: "Leonardo Balerdi" },
      { code: "ARG-8", name: "Enzo Fernandez" },
      { code: "ARG-9", name: "Alexis Mac Allister" },
      { code: "ARG-10", name: "Rodrigo De Paul" },
      { code: "ARG-11", name: "Exequiel Palacios" },
      { code: "ARG-12", name: "Leandro Paredes" },
      { code: "ARG-13", name: "Team Photo" },
      { code: "ARG-14", name: "Nico Paz" },
      { code: "ARG-15", name: "Franco Mastantuono" },
      { code: "ARG-16", name: "Nico Gonzalez" },
      { code: "ARG-17", name: "Lionel Messi" },
      { code: "ARG-18", name: "Lautaro Martinez" },
      { code: "ARG-19", name: "Julian Alvarez" },
      { code: "ARG-20", name: "Giuliano Simeone" },
    ],
  },
  {
    name: "Australia",
    stickers: [
      { code: "AUS-1", name: "Emblem" },
      { code: "AUS-2", name: "Mathew Ryan" },
      { code: "AUS-3", name: "Joe Gauci" },
      { code: "AUS-4", name: "Harry Souttar" },
      { code: "AUS-5", name: "Alessandro Circati" },
      { code: "AUS-6", name: "Jordan Bos" },
      { code: "AUS-7", name: "Aziz Behich" },
      { code: "AUS-8", name: "Cameron Burgess" },
      { code: "AUS-9", name: "Lewis Miller" },
      { code: "AUS-10", name: "Milos Degenek" },
      { code: "AUS-11", name: "Jackson Irvine" },
      { code: "AUS-12", name: "Riley McGree" },
      { code: "AUS-13", name: "Team Photo" },
      { code: "AUS-14", name: "Aiden O'Neill" },
      { code: "AUS-15", name: "Connor Metcalfe" },
      { code: "AUS-16", name: "Patrick Yazbek" },
      { code: "AUS-17", name: "Craig Goodwin" },
      { code: "AUS-18", name: "Kusini Vengi" },
      { code: "AUS-19", name: "Nestory Irankunda" },
      { code: "AUS-20", name: "Mohamed Touré" },
    ],
  },
  {
    name: "Austria",
    stickers: [
      { code: "AUT-1", name: "Emblem" },
      { code: "AUT-2", name: "Alexander Schlager" },
      { code: "AUT-3", name: "Patrick Pentz" },
      { code: "AUT-4", name: "David Alaba" },
      { code: "AUT-5", name: "Kevin Danso" },
      { code: "AUT-6", name: "Philipp Lienhart" },
      { code: "AUT-7", name: "Stefan Bosch" },
      { code: "AUT-8", name: "Phillipp Mwene" },
      { code: "AUT-9", name: "Alexander Prass" },
      { code: "AUT-10", name: "Xavier Schlager" },
      { code: "AUT-11", name: "Marcel Sabitzer" },
      { code: "AUT-12", name: "Konrad Laimer" },
      { code: "AUT-13", name: "Team Photo" },
      { code: "AUT-14", name: "Florian Grillitsch" },
      { code: "AUT-15", name: "Nicolas Seiwald" },
      { code: "AUT-16", name: "Romano Schmid" },
      { code: "AUT-17", name: "Patrick Wimmer" },
      { code: "AUT-18", name: "Christoph Baumgartner" },
      { code: "AUT-19", name: "Michael Gregoritsch" },
      { code: "AUT-20", name: "Marko Arnautović" },
    ],
  },
  {
    name: "Belgium",
    stickers: [
      { code: "BEL-1", name: "Emblem" },
      { code: "BEL-2", name: "Thibaut Courtois" },
      { code: "BEL-3", name: "Arthur Theate" },
      { code: "BEL-4", name: "Timothy Castagne" },
      { code: "BEL-5", name: "Zeno Debast" },
      { code: "BEL-6", name: "Brandon Mechele" },
      { code: "BEL-7", name: "Maxim De Cuyper" },
      { code: "BEL-8", name: "Thomas Meunier" },
      { code: "BEL-9", name: "Youri Tielemans" },
      { code: "BEL-10", name: "Amadou Onana" },
      { code: "BEL-11", name: "Nicolas Raskin" },
      { code: "BEL-12", name: "Alexis Saelemaekers" },
      { code: "BEL-13", name: "Team Photo" },
      { code: "BEL-14", name: "Hans Vanaken" },
      { code: "BEL-15", name: "Kevin De Bruyne" },
      { code: "BEL-16", name: "Jérémy Doku" },
      { code: "BEL-17", name: "Charles De Ketelaere" },
      { code: "BEL-18", name: "Leandro Trossard" },
      { code: "BEL-19", name: "Loïs Openda" },
      { code: "BEL-20", name: "Romelu Lukaku" },
    ],
  },
  {
    name: "Bosnia and Herzegovina",
    stickers: [
      { code: "BIH-1", name: "Emblem" },
      { code: "BIH-2", name: "Nikola Vasilj" },
      { code: "BIH-3", name: "Amer Dedic" },
      { code: "BIH-4", name: "Sead Kolasinac" },
      { code: "BIH-5", name: "Tarik Muharemovic" },
      { code: "BIH-6", name: "Nihad Mujakic" },
      { code: "BIH-7", name: "Nikola Katic" },
      { code: "BIH-8", name: "Amir Hadziahmetovic" },
      { code: "BIH-9", name: "Benjamin Tahirovic" },
      { code: "BIH-10", name: "Armin Gigovic" },
      { code: "BIH-11", name: "Ivan Sunjic" },
      { code: "BIH-12", name: "Ivan Basic" },
      { code: "BIH-13", name: "Team Photo" },
      { code: "BIH-14", name: "Dzenis Burnic" },
      { code: "BIH-15", name: "Esmir Bajraktarevic" },
      { code: "BIH-16", name: "Amar Memic" },
      { code: "BIH-17", name: "Ermedin Demirovic" },
      { code: "BIH-18", name: "Edin Dzeko" },
      { code: "BIH-19", name: "Samed Bazdar" },
      { code: "BIH-20", name: "Haris Tabakovic" },
    ],
  },
  {
    name: "Brazil",
    stickers: [
      { code: "BRA-1", name: "Emblem" },
      { code: "BRA-2", name: "Alisson" },
      { code: "BRA-3", name: "Bento" },
      { code: "BRA-4", name: "Marquinhos" },
      { code: "BRA-5", name: "Éder Militão" },
      { code: "BRA-6", name: "Gabriel Magalhães" },
      { code: "BRA-7", name: "Danilo" },
      { code: "BRA-8", name: "Wesley" },
      { code: "BRA-9", name: "Lucas Paquetá" },
      { code: "BRA-10", name: "Casemiro" },
      { code: "BRA-11", name: "Bruno Guimarães" },
      { code: "BRA-12", name: "Luiz Henrique" },
      { code: "BRA-13", name: "Team Photo" },
      { code: "BRA-14", name: "Vinicius Júnior" },
      { code: "BRA-15", name: "Rodrygo" },
      { code: "BRA-16", name: "João Pedro" },
      { code: "BRA-17", name: "Matheus Cunha" },
      { code: "BRA-18", name: "Gabriel Martinelli" },
      { code: "BRA-19", name: "Raphinha" },
      { code: "BRA-20", name: "Estévão" },
    ],
  },
  {
    name: "Canada",
    stickers: [
      { code: "CAN-1", name: "Emblem" },
      { code: "CAN-2", name: "Dayne St.Clair" },
      { code: "CAN-3", name: "Alphonso Davies" },
      { code: "CAN-4", name: "Alistair Johnston" },
      { code: "CAN-5", name: "Samuel Adekugbe" },
      { code: "CAN-6", name: "Riche Larvea" },
      { code: "CAN-7", name: "Derek Cornelius" },
      { code: "CAN-8", name: "Moïse Bombito" },
      { code: "CAN-9", name: "Kamal Miller" },
      { code: "CAN-10", name: "Stephen Eustáquio" },
      { code: "CAN-11", name: "Ismaël Koné" },
      { code: "CAN-12", name: "Jonathan Osorio" },
      { code: "CAN-13", name: "Team Photo" },
      { code: "CAN-14", name: "Jacob Shaffelburg" },
      { code: "CAN-15", name: "Mathieu Choinière" },
      { code: "CAN-16", name: "Niko Sigur" },
      { code: "CAN-17", name: "Tajon Buchanan" },
      { code: "CAN-18", name: "Liam Millar" },
      { code: "CAN-19", name: "Cyle Larin" },
      { code: "CAN-20", name: "Jonathan David" },
    ],
  },
  {
    name: "Ivory Coast",
    stickers: [
      { code: "CIV-1", name: "Emblem" },
      { code: "CIV-2", name: "Yahia Fofana" },
      { code: "CIV-3", name: "Ghislain Konan" },
      { code: "CIV-4", name: "Wilfried Singo" },
      { code: "CIV-5", name: "Odilon Kossounou" },
      { code: "CIV-6", name: "Evan Ndicka" },
      { code: "CIV-7", name: "Willy Boly" },
      { code: "CIV-8", name: "Emmanuel Agbadou" },
      { code: "CIV-9", name: "Ousmane Diomande" },
      { code: "CIV-10", name: "Franck Kessie" },
      { code: "CIV-11", name: "Seko Fofana" },
      { code: "CIV-12", name: "Ibrahim Sangare" },
      { code: "CIV-13", name: "Team Photo" },
      { code: "CIV-14", name: "Jean-Philippe Gbamin" },
      { code: "CIV-15", name: "Amad Diallo" },
      { code: "CIV-16", name: "Sébastien Haller" },
      { code: "CIV-17", name: "Simon Adringa" },
      { code: "CIV-18", name: "Yan Diomande" },
      { code: "CIV-19", name: "Evann Guessand" },
      { code: "CIV-20", name: "Oumar Diakite" },
    ],
  },
  {
    name: "Congo DR",
    stickers: [
      { code: "COD-1", name: "Emblem" },
      { code: "COD-2", name: "Lionel Mpasi" },
      { code: "COD-3", name: "Aaron Wan-Bissaka" },
      { code: "COD-4", name: "Axel Tuanzebe" },
      { code: "COD-5", name: "Arthur Masuaku" },
      { code: "COD-6", name: "Chancel Mbemba" },
      { code: "COD-7", name: "Joris Kayembe" },
      { code: "COD-8", name: "Charles Pickel" },
      { code: "COD-9", name: "Ngal'ayel Mukau" },
      { code: "COD-10", name: "Edo Kayembe" },
      { code: "COD-11", name: "Samuel Moutoussamy" },
      { code: "COD-12", name: "Noah Sadiki" },
      { code: "COD-13", name: "Team Photo" },
      { code: "COD-14", name: "Théo Bongonda" },
      { code: "COD-15", name: "Meschak Elia" },
      { code: "COD-16", name: "Yoane Wissa" },
      { code: "COD-17", name: "Brian Cipenga" },
      { code: "COD-18", name: "Fiston Mayele" },
      { code: "COD-19", name: "Cédric Bakambu" },
      { code: "COD-20", name: "Nathanaël Mbuku" },
    ],
  },
  {
    name: "Colombia",
    stickers: [
      { code: "COL-1", name: "Emblem" },
      { code: "COL-2", name: "Camilo Vargas" },
      { code: "COL-3", name: "David Ospina" },
      { code: "COL-4", name: "Dávinson Sánchez" },
      { code: "COL-5", name: "Yerry Mina" },
      { code: "COL-6", name: "Daniel Munoz" },
      { code: "COL-7", name: "Johan Mojica" },
      { code: "COL-8", name: "Jhon Lucumí" },
      { code: "COL-9", name: "Santiago Arias" },
      { code: "COL-10", name: "Jefferson Lerma" },
      { code: "COL-11", name: "Kevin Castaño" },
      { code: "COL-12", name: "Richard Rios" },
      { code: "COL-13", name: "Team Photo" },
      { code: "COL-14", name: "James Rodriguez" },
      { code: "COL-15", name: "Juan Fernando Quintero" },
      { code: "COL-16", name: "Jorge Carrascal" },
      { code: "COL-17", name: "Jhon Arias" },
      { code: "COL-18", name: "Jhon Cordova" },
      { code: "COL-19", name: "Luis Suarez" },
      { code: "COL-20", name: "Luis Diaz" },
    ],
  },
  {
    name: "Cape Verde",
    stickers: [
      { code: "CPV-1", name: "Emblem" },
      { code: "CPV-2", name: "Vozinha" },
      { code: "CPV-3", name: "Logan Costa" },
      { code: "CPV-4", name: "Pico" },
      { code: "CPV-5", name: "Diney" },
      { code: "CPV-6", name: "Steven Moreira" },
      { code: "CPV-7", name: "Wagner Pina" },
      { code: "CPV-8", name: "Joao Paulo" },
      { code: "CPV-9", name: "Yannick Semedo" },
      { code: "CPV-10", name: "Kevin Pina" },
      { code: "CPV-11", name: "Patrick Andrade" },
      { code: "CPV-12", name: "Jamiro Monteiro" },
      { code: "CPV-13", name: "Team Photo" },
      { code: "CPV-14", name: "Deroy Duarte" },
      { code: "CPV-15", name: "Garry Rodrigues" },
      { code: "CPV-16", name: "Jovane Cabral" },
      { code: "CPV-17", name: "Ryan Mendes" },
      { code: "CPV-18", name: "Dailon Livramento" },
      { code: "CPV-19", name: "Willy Semedo" },
      { code: "CPV-20", name: "Bebe" },
    ],
  },
  {
    name: "Croatia",
    stickers: [
      { code: "CRO-1", name: "Emblem" },
      { code: "CRO-2", name: "Dominik Livaković" },
      { code: "CRO-3", name: "Duje Caleta-Car" },
      { code: "CRO-4", name: "Josko Gvardiol" },
      { code: "CRO-5", name: "Josip Stanišić" },
      { code: "CRO-6", name: "Luka Vušković" },
      { code: "CRO-7", name: "Josip Sutalo" },
      { code: "CRO-8", name: "Kristijan Jakic" },
      { code: "CRO-9", name: "Luka Modrić" },
      { code: "CRO-10", name: "Mateo Kovacic" },
      { code: "CRO-11", name: "Martin Baturina" },
      { code: "CRO-12", name: "Lovro Majer" },
      { code: "CRO-13", name: "Team Photo" },
      { code: "CRO-14", name: "Mario Pasalic" },
      { code: "CRO-15", name: "Petar Sucic" },
      { code: "CRO-16", name: "Ivan Perišić" },
      { code: "CRO-17", name: "Marco Pasalic" },
      { code: "CRO-18", name: "Ante Budimir" },
      { code: "CRO-19", name: "Andrej Kramarić" },
      { code: "CRO-20", name: "Franjo Ivanovic" },
    ],
  },
  {
    name: "Curaçao",
    stickers: [
      { code: "CUW-1", name: "Emblem" },
      { code: "CUW-2", name: "Eloy Room" },
      { code: "CUW-3", name: "Armando Obispo" },
      { code: "CUW-4", name: "Sherel Floranus" },
      { code: "CUW-5", name: "Jurien Gaari" },
      { code: "CUW-6", name: "Joshua Brenet" },
      { code: "CUW-7", name: "Roshon Van Eijma" },
      { code: "CUW-8", name: "Shurandy Sambo" },
      { code: "CUW-9", name: "Livano Comenencia" },
      { code: "CUW-10", name: "Godfried Roemeratoe" },
      { code: "CUW-11", name: "Juninho Bacuna" },
      { code: "CUW-12", name: "Leandro Bacuna" },
      { code: "CUW-13", name: "Team Photo" },
      { code: "CUW-14", name: "Tahith Chong" },
      { code: "CUW-15", name: "Kenji Gorre" },
      { code: "CUW-16", name: "Jearl Margaritha" },
      { code: "CUW-17", name: "Jurgen Locadia" },
      { code: "CUW-18", name: "Jeremy Antonisse" },
      { code: "CUW-19", name: "Gervane Kastaneer" },
      { code: "CUW-20", name: "Sontje Hansen" },
    ],
  },
  {
    name: "Czechia",
    stickers: [
      { code: "CZE-1", name: "Emblem" },
      { code: "CZE-2", name: "Matej Kovar" },
      { code: "CZE-3", name: "Jindrich Stanek" },
      { code: "CZE-4", name: "Ladislav Krejci" },
      { code: "CZE-5", name: "Vladimir Coufal" },
      { code: "CZE-6", name: "Jaroslav Zeleny" },
      { code: "CZE-7", name: "Tomas Holes" },
      { code: "CZE-8", name: "David Zima" },
      { code: "CZE-9", name: "Michal Sadilek" },
      { code: "CZE-10", name: "Lukas Provod" },
      { code: "CZE-11", name: "Lukas Cerv" },
      { code: "CZE-12", name: "Tomas Soucek" },
      { code: "CZE-13", name: "Team Photo" },
      { code: "CZE-14", name: "Pavel Sulc" },
      { code: "CZE-15", name: "Matej Vydra" },
      { code: "CZE-16", name: "Vasil Kusej" },
      { code: "CZE-17", name: "Tomas Chory" },
      { code: "CZE-18", name: "Vacilav Cerny" },
      { code: "CZE-19", name: "Adam Hlozek" },
      { code: "CZE-20", name: "Patrik Schick" },
    ],
  },
  {
    name: "Ecuador",
    stickers: [
      { code: "ECU-1", name: "Emblem" },
      { code: "ECU-2", name: "Hernán Galíndez" },
      { code: "ECU-3", name: "Gonzalo Valle" },
      { code: "ECU-4", name: "Piero Hincapié" },
      { code: "ECU-5", name: "Pervis Estupiñán" },
      { code: "ECU-6", name: "Willian Pacho" },
      { code: "ECU-7", name: "Ángelo Preciado" },
      { code: "ECU-8", name: "Joel Ordóñez" },
      { code: "ECU-9", name: "Moises Caicedo" },
      { code: "ECU-10", name: "Alan Franco" },
      { code: "ECU-11", name: "Kendry Paez" },
      { code: "ECU-12", name: "Pedro Vite" },
      { code: "ECU-13", name: "Team Photo" },
      { code: "ECU-14", name: "John Veboah" },
      { code: "ECU-15", name: "Leonardo Campana" },
      { code: "ECU-16", name: "Gonzalo Plata" },
      { code: "ECU-17", name: "Nilson Angulo" },
      { code: "ECU-18", name: "Alan Minda" },
      { code: "ECU-19", name: "Kevin Rodriguez" },
      { code: "ECU-20", name: "Enner Valencia" },
    ],
  },
  {
    name: "Egypt",
    stickers: [
      { code: "EGY-1", name: "Emblem" },
      { code: "EGY-2", name: "Mohamed El Shenawy" },
      { code: "EGY-3", name: "Mohamed Hany" },
      { code: "EGY-4", name: "Mohamed Hamdy" },
      { code: "EGY-5", name: "Yasser Ibrahim" },
      { code: "EGY-6", name: "Khaled Sobhi" },
      { code: "EGY-7", name: "Ramy Rabia" },
      { code: "EGY-8", name: "Hossam Abdelmaguid" },
      { code: "EGY-9", name: "Ahmed Fatouh" },
      { code: "EGY-10", name: "Marwan Attia" },
      { code: "EGY-11", name: "Zizo" },
      { code: "EGY-12", name: "Hamdy Fathy" },
      { code: "EGY-13", name: "Team Photo" },
      { code: "EGY-14", name: "Mohamed Lasheen" },
      { code: "EGY-15", name: "Emam Ashour" },
      { code: "EGY-16", name: "Osama Faisal" },
      { code: "EGY-17", name: "Mohamed Salah" },
      { code: "EGY-18", name: "Mostafa Mohamed" },
      { code: "EGY-19", name: "Trezeguet" },
      { code: "EGY-20", name: "Omar Marsmoush" },
    ],
  },
  {
    name: "England",
    stickers: [
      { code: "ENG-1", name: "Emblem" },
      { code: "ENG-2", name: "Jordan Pickford" },
      { code: "ENG-3", name: "John Stones" },
      { code: "ENG-4", name: "Maric Guéhi" },
      { code: "ENG-5", name: "Ezri Konsa" },
      { code: "ENG-6", name: "Trent Alexander-Arnold" },
      { code: "ENG-7", name: "Reece James" },
      { code: "ENG-8", name: "Dan Burn" },
      { code: "ENG-9", name: "Jordan Henderson" },
      { code: "ENG-10", name: "Declan Rice" },
      { code: "ENG-11", name: "Jude Bellingham" },
      { code: "ENG-12", name: "Cole Palmer" },
      { code: "ENG-13", name: "Team Photo" },
      { code: "ENG-14", name: "Morgan Rogers" },
      { code: "ENG-15", name: "Anthony Gordon" },
      { code: "ENG-16", name: "Phil Foden" },
      { code: "ENG-17", name: "Bukayo Saka" },
      { code: "ENG-18", name: "Harry Kane" },
      { code: "ENG-19", name: "Marcus Rashford" },
      { code: "ENG-20", name: "Ollie Watkins" },
    ],
  },
  {
    name: "Spain",
    stickers: [
      { code: "ESP-1", name: "Emblem" },
      { code: "ESP-2", name: "Unai Simon" },
      { code: "ESP-3", name: "Robin Le Normand" },
      { code: "ESP-4", name: "Aymeric Laporte" },
      { code: "ESP-5", name: "Dean Huijsen" },
      { code: "ESP-6", name: "Pedro Porro" },
      { code: "ESP-7", name: "Dani Carvajal" },
      { code: "ESP-8", name: "Marc Cucurella" },
      { code: "ESP-9", name: "Martín Zubimendi" },
      { code: "ESP-10", name: "Rodri" },
      { code: "ESP-11", name: "Pedri" },
      { code: "ESP-12", name: "Fabian Ruiz" },
      { code: "ESP-13", name: "Team Photo" },
      { code: "ESP-14", name: "Mikel Merino" },
      { code: "ESP-15", name: "Lamine Yamal" },
      { code: "ESP-16", name: "Dani Olmo" },
      { code: "ESP-17", name: "Nico Williams" },
      { code: "ESP-18", name: "Ferran Torres" },
      { code: "ESP-19", name: "Álvaro Morata" },
      { code: "ESP-20", name: "Mikel Oyarzabal" },
    ],
  },
  {
    name: "France",
    stickers: [
      { code: "FRA-1", name: "Emblem" },
      { code: "FRA-2", name: "Mike Maignan" },
      { code: "FRA-3", name: "Theo Hernandez" },
      { code: "FRA-4", name: "William Saliba" },
      { code: "FRA-5", name: "Jules Kounde" },
      { code: "FRA-6", name: "Ibrahima Konate" },
      { code: "FRA-7", name: "Dayot Upamecano" },
      { code: "FRA-8", name: "Lucas Digne" },
      { code: "FRA-9", name: "Aurélien Tchouaméni" },
      { code: "FRA-10", name: "Eduardo Camavinga" },
      { code: "FRA-11", name: "Manu Kone" },
      { code: "FRA-12", name: "Adrien Rabiot" },
      { code: "FRA-13", name: "Team Photo" },
      { code: "FRA-14", name: "Michael Olise" },
      { code: "FRA-15", name: "Ousmane Dembele" },
      { code: "FRA-16", name: "Bradley Barcola" },
      { code: "FRA-17", name: "Désiré Doué" },
      { code: "FRA-18", name: "Kingsley Coman" },
      { code: "FRA-19", name: "Hugo Ekitike" },
      { code: "FRA-20", name: "Kylian Mbappe" },
    ],
  },
  {
    name: "Germany",
    stickers: [
      { code: "GER-1", name: "Emblem" },
      { code: "GER-2", name: "Marc-André ter Stegen" },
      { code: "GER-3", name: "Jonathan Tah" },
      { code: "GER-4", name: "David Raum" },
      { code: "GER-5", name: "Nico Schlotterbeck" },
      { code: "GER-6", name: "Antonio Rüdiger" },
      { code: "GER-7", name: "Waldemar Anton" },
      { code: "GER-8", name: "Ridle Baku" },
      { code: "GER-9", name: "Maximilian Mittelstadt" },
      { code: "GER-10", name: "Joshua Kimmich" },
      { code: "GER-11", name: "Florian Wirtz" },
      { code: "GER-12", name: "Felix Nmecha" },
      { code: "GER-13", name: "Team Photo" },
      { code: "GER-14", name: "Leon Goretzka" },
      { code: "GER-15", name: "Jamal Musiala" },
      { code: "GER-16", name: "Serge Gnabry" },
      { code: "GER-17", name: "Kai Havertz" },
      { code: "GER-18", name: "Leroy Sane" },
      { code: "GER-19", name: "Karim Adeyemi" },
      { code: "GER-20", name: "Nick Woltemade" },
    ],
  },
  {
    name: "Ghana",
    stickers: [
      { code: "GHA-1", name: "Emblem" },
      { code: "GHA-2", name: "Lawrence Ati Zigi" },
      { code: "GHA-3", name: "Tariq Lamptey" },
      { code: "GHA-4", name: "Mohammed Salisu" },
      { code: "GHA-5", name: "Alidu Seidu" },
      { code: "GHA-6", name: "Alexander Djiku" },
      { code: "GHA-7", name: "Gideon Mensah" },
      { code: "GHA-8", name: "Caleb Yirenkyi" },
      { code: "GHA-9", name: "Abdul Issahaku Fatawu" },
      { code: "GHA-10", name: "Thomas Partey" },
      { code: "GHA-11", name: "Salis Abdul Samed" },
      { code: "GHA-12", name: "Kamaldeen Sulemana" },
      { code: "GHA-13", name: "Team Photo" },
      { code: "GHA-14", name: "Mohammed Kudus" },
      { code: "GHA-15", name: "Inaki Williams" },
      { code: "GHA-16", name: "Jordan Ayew" },
      { code: "GHA-17", name: "Andrew Ayew" },
      { code: "GHA-18", name: "Joseph Paintsil" },
      { code: "GHA-19", name: "Osman Bukari" },
      { code: "GHA-20", name: "Antoine Semenyo" },
    ],
  },
  {
    name: "Haiti",
    stickers: [
      { code: "HAI-1", name: "Emblem" },
      { code: "HAI-2", name: "Johny Placide" },
      { code: "HAI-3", name: "Carlens Arcus" },
      { code: "HAI-4", name: "Martin Expérience" },
      { code: "HAI-5", name: "Jean-Kevin Duverne" },
      { code: "HAI-6", name: "Ricardo Adé" },
      { code: "HAI-7", name: "Duke Lacroix" },
      { code: "HAI-8", name: "Garven Metusala" },
      { code: "HAI-9", name: "Hannes Delcroix" },
      { code: "HAI-10", name: "Leverton Pierre" },
      { code: "HAI-11", name: "Danley Jean Jacques" },
      { code: "HAI-12", name: "Jean-Ricner Bellegarde" },
      { code: "HAI-13", name: "Team Photo" },
      { code: "HAI-14", name: "Christopher Attys" },
      { code: "HAI-15", name: "Derrick Etienne Jr." },
      { code: "HAI-16", name: "Josue Casimir" },
      { code: "HAI-17", name: "Ruben Providence" },
      { code: "HAI-18", name: "Duckens Nazon" },
      { code: "HAI-19", name: "Louicius Deedson" },
      { code: "HAI-20", name: "Frantzdy Pierrot" },
    ],
  },
  {
    name: "Iran",
    stickers: [
      { code: "IRN-1", name: "Emblem" },
      { code: "IRN-2", name: "Alirez Beiranvand" },
      { code: "IRN-3", name: "Morteza Pouraliganji" },
      { code: "IRN-4", name: "Ehsan Hajsafi" },
      { code: "IRN-5", name: "Milad Mohammadi" },
      { code: "IRN-6", name: "Shojae Khalilzadeh" },
      { code: "IRN-7", name: "Ramin Rezaeian" },
      { code: "IRN-8", name: "Hossein Kanaani" },
      { code: "IRN-9", name: "Sadegh Moharrami" },
      { code: "IRN-10", name: "Saleh Hardani" },
      { code: "IRN-11", name: "Saeed Ezatolahi" },
      { code: "IRN-12", name: "Saman Ghoddos" },
      { code: "IRN-13", name: "Team Photo" },
      { code: "IRN-14", name: "Omid Noorafkan" },
      { code: "IRN-15", name: "Roozbeh Cheshmi" },
      { code: "IRN-16", name: "Mohammad Mohebi" },
      { code: "IRN-17", name: "Sardar Azmoun" },
      { code: "IRN-18", name: "Mehdi Taremi" },
      { code: "IRN-19", name: "Alireza Jahanbakhsh" },
      { code: "IRN-20", name: "Ali Gholizadeh" },
    ],
  },
  {
    name: "Iraq",
    stickers: [
      { code: "IRQ-1", name: "Emblem" },
      { code: "IRQ-2", name: "Jalal Hassan" },
      { code: "IRQ-3", name: "Rebin Sulaka" },
      { code: "IRQ-4", name: "Hussein Ali" },
      { code: "IRQ-5", name: "Akam Hashem" },
      { code: "IRQ-6", name: "Merchas Doski" },
      { code: "IRQ-7", name: "Zaid Tahseen" },
      { code: "IRQ-8", name: "Manaf Younis" },
      { code: "IRQ-9", name: "Zidane Iqbal" },
      { code: "IRQ-10", name: "Amir Al-Ammari" },
      { code: "IRQ-11", name: "Ibrahim Bavesh" },
      { code: "IRQ-12", name: "Ali Jasim" },
      { code: "IRQ-13", name: "Team Photo" },
      { code: "IRQ-14", name: "Youssef Amyn" },
      { code: "IRQ-15", name: "Aimar Sher" },
      { code: "IRQ-16", name: "Marko Farji" },
      { code: "IRQ-17", name: "Osama Rashid" },
      { code: "IRQ-18", name: "Ali Al-Hamadi" },
      { code: "IRQ-19", name: "Aymen Hussein" },
      { code: "IRQ-20", name: "Mohanad Ali" },
    ],
  },
  {
    name: "Jordan",
    stickers: [
      { code: "JOR-1", name: "Emblem" },
      { code: "JOR-2", name: "Yazeed Abulaila" },
      { code: "JOR-3", name: "Ihsan Haddad" },
      { code: "JOR-4", name: "Mohammad Abu Hashish" },
      { code: "JOR-5", name: "Yazan Al-Arab" },
      { code: "JOR-6", name: "Abdallah Nasib" },
      { code: "JOR-7", name: "Saleem Obaid" },
      { code: "JOR-8", name: "Mohammad Abualnadi" },
      { code: "JOR-9", name: "Ibrahim Saadeh" },
      { code: "JOR-10", name: "Nizar Al-Rashdan" },
      { code: "JOR-11", name: "Noor Al-Rawabdeh" },
      { code: "JOR-12", name: "Mohannad Abu Taha" },
      { code: "JOR-13", name: "Team Photo" },
      { code: "JOR-14", name: "Amer Jamous" },
      { code: "JOR-15", name: "Mousa Al-Taamari" },
      { code: "JOR-16", name: "Yazan Al-Naimat" },
      { code: "JOR-17", name: "Mahmoud Al-Mardi" },
      { code: "JOR-18", name: "Ali Olwan" },
      { code: "JOR-19", name: "Mohammad Abu Zrayq" },
      { code: "JOR-20", name: "Ibrahim Sabra" },
    ],
  },
  {
    name: "Japan",
    stickers: [
      { code: "JPN-1", name: "Emblem" },
      { code: "JPN-2", name: "Zion Suzuki" },
      { code: "JPN-3", name: "Henry Heroki Mochizuki" },
      { code: "JPN-4", name: "Ayumu Seko" },
      { code: "JPN-5", name: "Junnosuke Suzuki" },
      { code: "JPN-6", name: "Shogo Taniguchi" },
      { code: "JPN-7", name: "Tsuyoshi Watanabe" },
      { code: "JPN-8", name: "Kaishu Sano" },
      { code: "JPN-9", name: "Yuki Soma" },
      { code: "JPN-10", name: "Ao Tanaka" },
      { code: "JPN-11", name: "Daichi Kamada" },
      { code: "JPN-12", name: "Takefusa Kubo" },
      { code: "JPN-13", name: "Team Photo" },
      { code: "JPN-14", name: "Ritsu Doan" },
      { code: "JPN-15", name: "Keito Nakamura" },
      { code: "JPN-16", name: "Takumi Minamino" },
      { code: "JPN-17", name: "Shuto Machino" },
      { code: "JPN-18", name: "Junya Ito" },
      { code: "JPN-19", name: "Koki Ogawa" },
      { code: "JPN-20", name: "Ayase Ueda" },
    ],
  },
  {
    name: "South Korea",
    stickers: [
      { code: "KOR-1", name: "Emblem" },
      { code: "KOR-2", name: "Hyeon-woo Jo" },
      { code: "KOR-3", name: "Seung-Gyu Kim" },
      { code: "KOR-4", name: "Min-jae Kim" },
      { code: "KOR-5", name: "Yu-min Cho" },
      { code: "KOR-6", name: "Young-woo Seol" },
      { code: "KOR-7", name: "Han-beom Lee" },
      { code: "KOR-8", name: "Tae-seok Lee" },
      { code: "KOR-9", name: "Myung-jae Lee" },
      { code: "KOR-10", name: "Jae-sung Lee" },
      { code: "KOR-11", name: "In-beom Hwang" },
      { code: "KOR-12", name: "Kang-in Lee" },
      { code: "KOR-13", name: "Team Photo" },
      { code: "KOR-14", name: "Seung-ho Paik" },
      { code: "KOR-15", name: "Jens Castrop" },
      { code: "KOR-16", name: "Dongg-yeong Lee" },
      { code: "KOR-17", name: "Gue-sung Cho" },
      { code: "KOR-18", name: "Heung-min Son" },
      { code: "KOR-19", name: "Hee-chan Hwang" },
      { code: "KOR-20", name: "Hyeon-Gyu Oh" },
    ],
  },
  {
    name: "Saudi Arabia",
    stickers: [
      { code: "KSA-1", name: "Emblem" },
      { code: "KSA-2", name: "Nawaf Alaqidi" },
      { code: "KSA-3", name: "Abdulrahman Al-Sanbi" },
      { code: "KSA-4", name: "Saud Abdulhamid" },
      { code: "KSA-5", name: "Nawaf Bouwashl" },
      { code: "KSA-6", name: "Jihad Thakri" },
      { code: "KSA-7", name: "Moteb Al-Harbi" },
      { code: "KSA-8", name: "Hassan Altambakti" },
      { code: "KSA-9", name: "Musab Aljuwayr" },
      { code: "KSA-10", name: "Ziyad Aljohani" },
      { code: "KSA-11", name: "Abdullah Alkhaibari" },
      { code: "KSA-12", name: "Nasser Aldawsari" },
      { code: "KSA-13", name: "Team Photo" },
      { code: "KSA-14", name: "Saleh Abu Alshamat" },
      { code: "KSA-15", name: "Marwan Alsahafi" },
      { code: "KSA-16", name: "Salem Aldawsari" },
      { code: "KSA-17", name: "Abdulrahman Al-Aboud" },
      { code: "KSA-18", name: "Feras Akbrikan" },
      { code: "KSA-19", name: "Saleh Alshehri" },
      { code: "KSA-20", name: "Abdullah Al-Hamdan" },
    ],
  },
  {
    name: "Morocco",
    stickers: [
      { code: "MAR-1", name: "Emblem" },
      { code: "MAR-2", name: "Yassine Bounou" },
      { code: "MAR-3", name: "Munir El Kajoui" },
      { code: "MAR-4", name: "Achraf Hakimi" },
      { code: "MAR-5", name: "Noussair Mazraoui" },
      { code: "MAR-6", name: "Nayef Aguerd" },
      { code: "MAR-7", name: "Roman Saiss" },
      { code: "MAR-8", name: "Jawad El Yamio" },
      { code: "MAR-9", name: "Adam Masina" },
      { code: "MAR-10", name: "Sofyan Amrabat" },
      { code: "MAR-11", name: "Azzedine Ounahi" },
      { code: "MAR-12", name: "Eliesse Ben Seghir" },
      { code: "MAR-13", name: "Team Photo" },
      { code: "MAR-14", name: "Bilal El Khannouss" },
      { code: "MAR-15", name: "Ismael Saibari" },
      { code: "MAR-16", name: "Youssef En-Nesyri" },
      { code: "MAR-17", name: "Abde Ezzalzouli" },
      { code: "MAR-18", name: "Soufiane Rahimi" },
      { code: "MAR-19", name: "Brahim Diaz" },
      { code: "MAR-20", name: "Ayoub El Kaabi" },
    ],
  },
  {
    name: "Mexico",
    stickers: [
      { code: "MEX-1", name: "Emblem" },
      { code: "MEX-2", name: "Luis Malagón" },
      { code: "MEX-3", name: "Johan Vasquez" },
      { code: "MEX-4", name: "Jorge Sánchez" },
      { code: "MEX-5", name: "Cesar Montes" },
      { code: "MEX-6", name: "Jesus Gallardo" },
      { code: "MEX-7", name: "Israel Reyes" },
      { code: "MEX-8", name: "Diego Lainez" },
      { code: "MEX-9", name: "Carlos Rodriguez" },
      { code: "MEX-10", name: "Edson Alvarez" },
      { code: "MEX-11", name: "Orbelin Pineda" },
      { code: "MEX-12", name: "Marcel Ruiz" },
      { code: "MEX-13", name: "Team Photo" },
      { code: "MEX-14", name: "Érick Sánchez" },
      { code: "MEX-15", name: "Hirving Lozano" },
      { code: "MEX-16", name: "Santiago Giménez" },
      { code: "MEX-17", name: "Raúl Jiménez" },
      { code: "MEX-18", name: "Alexis Vega" },
      { code: "MEX-19", name: "Roberto Alvarado" },
      { code: "MEX-20", name: "Cesar Huerta" },
    ],
  },
  {
    name: "Netherlands",
    stickers: [
      { code: "NED-1", name: "Emblem" },
      { code: "NED-2", name: "Bart Verbruggen" },
      { code: "NED-3", name: "Virgil van Dijk" },
      { code: "NED-4", name: "Micky van de Ven" },
      { code: "NED-5", name: "Jurien Timber" },
      { code: "NED-6", name: "Denzel Dumfries" },
      { code: "NED-7", name: "Nathan Aké" },
      { code: "NED-8", name: "Jereme Frimpong" },
      { code: "NED-9", name: "Jan Paul van Hecke" },
      { code: "NED-10", name: "Tijjani Reijnders" },
      { code: "NED-11", name: "Ryan Gravenberch" },
      { code: "NED-12", name: "Teun Koopmeiners" },
      { code: "NED-13", name: "Team Photo" },
      { code: "NED-14", name: "Frenkie de Jong" },
      { code: "NED-15", name: "Xavi Simons" },
      { code: "NED-16", name: "Justin Kluivert" },
      { code: "NED-17", name: "Memphis Depay" },
      { code: "NED-18", name: "Donyell Malen" },
      { code: "NED-19", name: "Wout Weghorst" },
      { code: "NED-20", name: "Cody Gakpo" },
    ],
  },
  {
    name: "Norway",
    stickers: [
      { code: "NOR-1", name: "Emblem" },
      { code: "NOR-2", name: "Orjan Nyland" },
      { code: "NOR-3", name: "Julian Ryerson" },
      { code: "NOR-4", name: "Leo Ostigård" },
      { code: "NOR-5", name: "Kristoffer Vassbakk Ajer" },
      { code: "NOR-6", name: "Marcus Holmgren Pedersen" },
      { code: "NOR-7", name: "David Møller Wolfe" },
      { code: "NOR-8", name: "Torbjørn Heggem" },
      { code: "NOR-9", name: "Morten Thorsby" },
      { code: "NOR-10", name: "Martin Ødegaard" },
      { code: "NOR-11", name: "Sander Berge" },
      { code: "NOR-12", name: "Andreas Schjelderup" },
      { code: "NOR-13", name: "Team Photo" },
      { code: "NOR-14", name: "Patrick Berg" },
      { code: "NOR-15", name: "Erling Haaland" },
      { code: "NOR-16", name: "Alexander Sørloth" },
      { code: "NOR-17", name: "Aron Dønnum" },
      { code: "NOR-18", name: "Jorgen Strand Larsen" },
      { code: "NOR-19", name: "Antonio Nusa" },
      { code: "NOR-20", name: "Oscar Bobb" },
    ],
  },
  {
    name: "New Zealand",
    stickers: [
      { code: "NZL-1", name: "Emblem" },
      { code: "NZL-2", name: "Max Crocombe Payne" },
      { code: "NZL-3", name: "Alex Paulsen" },
      { code: "NZL-4", name: "Michael Boxall" },
      { code: "NZL-5", name: "Liberato Cacace" },
      { code: "NZL-6", name: "Tim Payne" },
      { code: "NZL-7", name: "Tyler Bindon" },
      { code: "NZL-8", name: "Francis de Vries" },
      { code: "NZL-9", name: "Finn Surman" },
      { code: "NZL-10", name: "Joe Bell" },
      { code: "NZL-11", name: "Sarpreet Singh" },
      { code: "NZL-12", name: "Ryan Thomas" },
      { code: "NZL-13", name: "Team Photo" },
      { code: "NZL-14", name: "Matthew Garbett" },
      { code: "NZL-15", name: "Marko Stamenić" },
      { code: "NZL-16", name: "Ben Old" },
      { code: "NZL-17", name: "Chris Wood" },
      { code: "NZL-18", name: "Elijah Just" },
      { code: "NZL-19", name: "Callum McCowatt" },
      { code: "NZL-20", name: "Kosta Barbarouses" },
    ],
  },
  {
    name: "Panama",
    stickers: [
      { code: "PAN-1", name: "Emblem" },
      { code: "PAN-2", name: "Orlando Mosquera" },
      { code: "PAN-3", name: "Luis Mejia" },
      { code: "PAN-4", name: "Fidel Escobar" },
      { code: "PAN-5", name: "Andres Andrade" },
      { code: "PAN-6", name: "Michael Amir Murillo" },
      { code: "PAN-7", name: "Eric Davis" },
      { code: "PAN-8", name: "Jose Cordoba" },
      { code: "PAN-9", name: "Cesar Blackman" },
      { code: "PAN-10", name: "Cristian Martinez" },
      { code: "PAN-11", name: "Aníbal Godoy" },
      { code: "PAN-12", name: "Adalberto Carrasquilla" },
      { code: "PAN-13", name: "Team Photo" },
      { code: "PAN-14", name: "Édgar Bárcenas" },
      { code: "PAN-15", name: "Carlos Harvey" },
      { code: "PAN-16", name: "Ismael Díaz" },
      { code: "PAN-17", name: "Jose Fajardo" },
      { code: "PAN-18", name: "Cecilio Waterman" },
      { code: "PAN-19", name: "Jose Luiz Rodriguez" },
      { code: "PAN-20", name: "Alberto Quintero" },
    ],
  },
  {
    name: "Paraguay",
    stickers: [
      { code: "PAR-1", name: "Emblem" },
      { code: "PAR-2", name: "Roberto Fernandez" },
      { code: "PAR-3", name: "Orlando Gill" },
      { code: "PAR-4", name: "Gustavo Gomez" },
      { code: "PAR-5", name: "Fabián Balbuena" },
      { code: "PAR-6", name: "Juan José Cáceres" },
      { code: "PAR-7", name: "Omar Alderete" },
      { code: "PAR-8", name: "Junior Alonso" },
      { code: "PAR-9", name: "Mathías Villasanti" },
      { code: "PAR-10", name: "Diego Gomez" },
      { code: "PAR-11", name: "Damián Bobadilla" },
      { code: "PAR-12", name: "Andres Cubas" },
      { code: "PAR-13", name: "Team Photo" },
      { code: "PAR-14", name: "Matias Galarza Fonda" },
      { code: "PAR-15", name: "Julio Enciso" },
      { code: "PAR-16", name: "Alejandro Romero Gamarra" },
      { code: "PAR-17", name: "Miguel Almirón" },
      { code: "PAR-18", name: "Ramon Sosa" },
      { code: "PAR-19", name: "Angel Romero" },
      { code: "PAR-20", name: "Antonio Sanabria" },
    ],
  },
  {
    name: "Portugal",
    stickers: [
      { code: "POR-1", name: "Emblem" },
      { code: "POR-2", name: "Diogo Costa" },
      { code: "POR-3", name: "Jose Sa" },
      { code: "POR-4", name: "Ruben Dias" },
      { code: "POR-5", name: "João Cancelo" },
      { code: "POR-6", name: "Diogo Dalot" },
      { code: "POR-7", name: "Nuno Mendes" },
      { code: "POR-8", name: "Gonçalo Inácio" },
      { code: "POR-9", name: "Bernardo Silva" },
      { code: "POR-10", name: "Bruno Fernandes" },
      { code: "POR-11", name: "Ruben Neves" },
      { code: "POR-12", name: "Vitinha" },
      { code: "POR-13", name: "Team Photo" },
      { code: "POR-14", name: "João Neves" },
      { code: "POR-15", name: "Cristiano Ronaldo" },
      { code: "POR-16", name: "Francisco Trincao" },
      { code: "POR-17", name: "João Felix" },
      { code: "POR-18", name: "Gonçalo Ramos" },
      { code: "POR-19", name: "Pedro Neto" },
      { code: "POR-20", name: "Rafael Leão" },
    ],
  },
  {
    name: "Qatar",
    stickers: [
      { code: "QAT-1", name: "Emblem" },
      { code: "QAT-2", name: "Meshaal Barsham" },
      { code: "QAT-3", name: "Sultan Albrake" },
      { code: "QAT-4", name: "Lucas Mendes" },
      { code: "QAT-5", name: "Homam Ahmed" },
      { code: "QAT-6", name: "Boualem Khoukhi" },
      { code: "QAT-7", name: "Pedro Miguel" },
      { code: "QAT-8", name: "Tarek Salman" },
      { code: "QAT-9", name: "Mohamed Al-Mannai" },
      { code: "QAT-10", name: "Karim Boudiaf" },
      { code: "QAT-11", name: "Assim Madibo" },
      { code: "QAT-12", name: "Ahmed Fatehi" },
      { code: "QAT-13", name: "Team Photo" },
      { code: "QAT-14", name: "Mohammed Waad" },
      { code: "QAT-15", name: "Abdulaziz Hatem" },
      { code: "QAT-16", name: "Hassan Al-Haydos" },
      { code: "QAT-17", name: "Edmilson Junior" },
      { code: "QAT-18", name: "Akram Hassan Afif" },
      { code: "QAT-19", name: "Ahmed Al Ganehi" },
      { code: "QAT-20", name: "Almoez Ali" },
    ],
  },
  {
    name: "South Africa",
    stickers: [
      { code: "RSA-1", name: "Emblem" },
      { code: "RSA-2", name: "Ronwen Williams" },
      { code: "RSA-3", name: "Sipho Chaine" },
      { code: "RSA-4", name: "Aubrey Modiba" },
      { code: "RSA-5", name: "Samukele Kabini" },
      { code: "RSA-6", name: "Mbekezeli Mbokazi" },
      { code: "RSA-7", name: "Khulumani Ndamane" },
      { code: "RSA-8", name: "Siyabonga Ngezana" },
      { code: "RSA-9", name: "Khuliso Mudau" },
      { code: "RSA-10", name: "Nkosinathi Sibisi" },
      { code: "RSA-11", name: "Teboho Mokoena" },
      { code: "RSA-12", name: "Thalente Mbatha" },
      { code: "RSA-13", name: "Team Photo" },
      { code: "RSA-14", name: "Bathasi Aubaas" },
      { code: "RSA-15", name: "Yaya Sithole" },
      { code: "RSA-16", name: "Sipho Mbule" },
      { code: "RSA-17", name: "Lyle Foster" },
      { code: "RSA-18", name: "Iqraam Rayners" },
      { code: "RSA-19", name: "Mohau Nkota" },
      { code: "RSA-20", name: "Oswin Appollis" },
    ],
  },
  {
    name: "Scotland",
    stickers: [
      { code: "SCO-1", name: "Emblem" },
      { code: "SCO-2", name: "Angus Gunn" },
      { code: "SCO-3", name: "Jack Hendry" },
      { code: "SCO-4", name: "Kieran Tierney" },
      { code: "SCO-5", name: "Aaron Hickey" },
      { code: "SCO-6", name: "Andrew Robertson" },
      { code: "SCO-7", name: "Scott McKenna" },
      { code: "SCO-8", name: "John Souttar" },
      { code: "SCO-9", name: "Anthony Ralston" },
      { code: "SCO-10", name: "Grant Hanley" },
      { code: "SCO-11", name: "Scott McTominay" },
      { code: "SCO-12", name: "Billy Gilmour" },
      { code: "SCO-13", name: "Team Photo" },
      { code: "SCO-14", name: "Lewis Ferguson" },
      { code: "SCO-15", name: "Ryan Christie" },
      { code: "SCO-16", name: "Kenny McLean" },
      { code: "SCO-17", name: "John McGinn" },
      { code: "SCO-18", name: "Lyndon Dykes" },
      { code: "SCO-19", name: "Che Adams" },
      { code: "SCO-20", name: "Ben Gannon-Doak" },
    ],
  },
  {
    name: "Senegal",
    stickers: [
      { code: "SEN-1", name: "Emblem" },
      { code: "SEN-2", name: "Eduardo Mendy" },
      { code: "SEN-3", name: "Yehvann Diouf" },
      { code: "SEN-4", name: "Moussa Niakhaté" },
      { code: "SEN-5", name: "Abdoulaye Seck" },
      { code: "SEN-6", name: "Ismail Jakobs" },
      { code: "SEN-7", name: "El Hadji Malick Diouf" },
      { code: "SEN-8", name: "Kalidou Koulibaly" },
      { code: "SEN-9", name: "Idrissa Gana Gueye" },
      { code: "SEN-10", name: "Pape Matar Sarr" },
      { code: "SEN-11", name: "Pape Gueye" },
      { code: "SEN-12", name: "Habib Diarra" },
      { code: "SEN-13", name: "Team Photo" },
      { code: "SEN-14", name: "Lamine Camara" },
      { code: "SEN-15", name: "Sadio Mane" },
      { code: "SEN-16", name: "Ismaïla Sarr" },
      { code: "SEN-17", name: "Boulaye Dia" },
      { code: "SEN-18", name: "Iliman Ndiaye" },
      { code: "SEN-19", name: "Nicolas Jackson" },
      { code: "SEN-20", name: "Krepin Diatta" },
    ],
  },
  {
    name: "Switzerland",
    stickers: [
      { code: "SUI-1", name: "Emblem" },
      { code: "SUI-2", name: "Gregor Kobel" },
      { code: "SUI-3", name: "Yvon Mvogo" },
      { code: "SUI-4", name: "Manuel Akanji" },
      { code: "SUI-5", name: "Ricardo Rodriguez" },
      { code: "SUI-6", name: "Nico Elvedi" },
      { code: "SUI-7", name: "Aurèle Amenda" },
      { code: "SUI-8", name: "Silvan Widmer" },
      { code: "SUI-9", name: "Granit Xhaka" },
      { code: "SUI-10", name: "Denis Zakaria" },
      { code: "SUI-11", name: "Remo Freuler" },
      { code: "SUI-12", name: "Fabian Rieder" },
      { code: "SUI-13", name: "Team Photo" },
      { code: "SUI-14", name: "Ardon Jashari" },
      { code: "SUI-15", name: "Johan Manzambi" },
      { code: "SUI-16", name: "Michel Aebischer" },
      { code: "SUI-17", name: "Breel Embolo" },
      { code: "SUI-18", name: "Ruben Vargas" },
      { code: "SUI-19", name: "Dan Ndoye" },
      { code: "SUI-20", name: "Zeki Amdouni" },
    ],
  },
  {
    name: "Sweden",
    stickers: [
      { code: "SWE-1", name: "Emblem" },
      { code: "SWE-2", name: "Victor Johansson" },
      { code: "SWE-3", name: "Isak Hien" },
      { code: "SWE-4", name: "Gabriel Gudmundsson" },
      { code: "SWE-5", name: "Emil Holm" },
      { code: "SWE-6", name: "Victor Nilsson Lindelöf" },
      { code: "SWE-7", name: "Gustaf Lagerbielke" },
      { code: "SWE-8", name: "Lucas Bergvall" },
      { code: "SWE-9", name: "Hugo Larsson" },
      { code: "SWE-10", name: "Jesper Karlström" },
      { code: "SWE-11", name: "Yasin Ayari" },
      { code: "SWE-12", name: "Mattias Svanberg" },
      { code: "SWE-13", name: "Team Photo" },
      { code: "SWE-14", name: "Daniel Svensson" },
      { code: "SWE-15", name: "Ken Sema" },
      { code: "SWE-16", name: "Roony Bardghji" },
      { code: "SWE-17", name: "Dejan Kulusevski" },
      { code: "SWE-18", name: "Anthony Elanga" },
      { code: "SWE-19", name: "Alexander Isak" },
      { code: "SWE-20", name: "Viktor Gyökeres" },
    ],
  },
  {
    name: "Tunisia",
    stickers: [
      { code: "TUN-1", name: "Emblem" },
      { code: "TUN-2", name: "Bechir Ben Said" },
      { code: "TUN-3", name: "Aymen Dahmen" },
      { code: "TUN-4", name: "Van Valery" },
      { code: "TUN-5", name: "Montassar Talbi" },
      { code: "TUN-6", name: "Yassine Meriah" },
      { code: "TUN-7", name: "Ali Abdi" },
      { code: "TUN-8", name: "Dylan Bronn" },
      { code: "TUN-9", name: "Ellyes Skhiri" },
      { code: "TUN-10", name: "Aissa Laidouni" },
      { code: "TUN-11", name: "Ferjani Sassi" },
      { code: "TUN-12", name: "Mohamed Ali Ben Romdhane" },
      { code: "TUN-13", name: "Team Photo" },
      { code: "TUN-14", name: "Hannibal Mejbri" },
      { code: "TUN-15", name: "Elias Achouri" },
      { code: "TUN-16", name: "Elias Saad" },
      { code: "TUN-17", name: "Hazem Mastouri" },
      { code: "TUN-18", name: "Ismael Gharbi" },
      { code: "TUN-19", name: "Sayfallah Ltaief" },
      { code: "TUN-20", name: "Naim Sliti" },
    ],
  },
  {
    name: "Türkiye",
    stickers: [
      { code: "TUR-1", name: "Emblem" },
      { code: "TUR-2", name: "Ugurcan Cakir" },
      { code: "TUR-3", name: "Mert Muldur" },
      { code: "TUR-4", name: "Zeki Celik" },
      { code: "TUR-5", name: "Abdulkerim Bardakci" },
      { code: "TUR-6", name: "Caglar Soyunku" },
      { code: "TUR-7", name: "Merih Demiral" },
      { code: "TUR-8", name: "Ferdi Kadioglu" },
      { code: "TUR-9", name: "Kaan Ayhan" },
      { code: "TUR-10", name: "Ismail Yuksek" },
      { code: "TUR-11", name: "Hakan Calhanoglu" },
      { code: "TUR-12", name: "Orkun Kokcu" },
      { code: "TUR-13", name: "Team Photo" },
      { code: "TUR-14", name: "Arda Guler" },
      { code: "TUR-15", name: "Irfan Can Kahvecu" },
      { code: "TUR-16", name: "Yunus Akgun" },
      { code: "TUR-17", name: "Can Uzun" },
      { code: "TUR-18", name: "Baris Alper Yilmaz" },
      { code: "TUR-19", name: "Kerem Akturkoglu" },
      { code: "TUR-20", name: "Kenan Yildiz" },
    ],
  },
  {
    name: "Uruguay",
    stickers: [
      { code: "URU-1", name: "Emblem" },
      { code: "URU-2", name: "Sergio Rochet" },
      { code: "URU-3", name: "Santiago Mele" },
      { code: "URU-4", name: "Ronald Araujo" },
      { code: "URU-5", name: "José María Giménez" },
      { code: "URU-6", name: "Sebastian Caceres" },
      { code: "URU-7", name: "Mathias Olivera" },
      { code: "URU-8", name: "Guillermo Varela" },
      { code: "URU-9", name: "Nahitan Nandez" },
      { code: "URU-10", name: "Federico Valverde" },
      { code: "URU-11", name: "Giorgian De Arrascaeta" },
      { code: "URU-12", name: "Rodrigo Bentancur" },
      { code: "URU-13", name: "Team Photo" },
      { code: "URU-14", name: "Manuel Ugarte" },
      { code: "URU-15", name: "Nicolás de la Cruz" },
      { code: "URU-16", name: "Maxi Araujo" },
      { code: "URU-17", name: "Darwin Núñez" },
      { code: "URU-18", name: "Federico Viñas" },
      { code: "URU-19", name: "Rodrigo Aguirre" },
      { code: "URU-20", name: "Facundo Pellistri" },
    ],
  },
  {
    name: "United States",
    stickers: [
      { code: "USA-1", name: "Emblem" },
      { code: "USA-2", name: "Matt Freese" },
      { code: "USA-3", name: "Chris Richards" },
      { code: "USA-4", name: "Tim Ream" },
      { code: "USA-5", name: "Mark McKenzie" },
      { code: "USA-6", name: "Alex Freeman" },
      { code: "USA-7", name: "Antonee Robinson" },
      { code: "USA-8", name: "Tyler Adams" },
      { code: "USA-9", name: "Tanner Tessmann" },
      { code: "USA-10", name: "Weston McKennie" },
      { code: "USA-11", name: "Christian Roldan" },
      { code: "USA-12", name: "Timothy Weah" },
      { code: "USA-13", name: "Team Photo" },
      { code: "USA-14", name: "Diego Luna" },
      { code: "USA-15", name: "Malim Tillman" },
      { code: "USA-16", name: "Christian Pulisic" },
      { code: "USA-17", name: "Brenden Aaronson" },
      { code: "USA-18", name: "Ricardo Pepi" },
      { code: "USA-19", name: "Haji Wright" },
      { code: "USA-20", name: "Folarin Balogun" },
    ],
  },
  {
    name: "Uzbekistan",
    stickers: [
      { code: "UZB-1", name: "Emblem" },
      { code: "UZB-2", name: "Utkir Yusupov" },
      { code: "UZB-3", name: "Farrukh Savfiev" },
      { code: "UZB-4", name: "Sherzod Nasrullaev" },
      { code: "UZB-5", name: "Umar Eshmurodov" },
      { code: "UZB-6", name: "Husniddin Aliqulov" },
      { code: "UZB-7", name: "Rustamjon Ashurmatov" },
      { code: "UZB-8", name: "Khojiakbar Alijonov" },
      { code: "UZB-9", name: "Abdukodir Khusanov" },
      { code: "UZB-10", name: "Odiljon Hamrobekov" },
      { code: "UZB-11", name: "Otabek Shukurov" },
      { code: "UZB-12", name: "Jamshid Iskanderov" },
      { code: "UZB-13", name: "Team Photo" },
      { code: "UZB-14", name: "Azizbek Turgunboev" },
      { code: "UZB-15", name: "Khojimat Erkinov" },
      { code: "UZB-16", name: "Eldor Shomurodov" },
      { code: "UZB-17", name: "Oston Urunov" },
      { code: "UZB-18", name: "Jaloliddin Masharipov" },
      { code: "UZB-19", name: "Igor Sergeev" },
      { code: "UZB-20", name: "Abbosbek Fayzullaev" },
    ],
  },
  {
    name: "FIFA World Cup History",
    stickers: [
      { code: "FWC-9", name: "Italy 1934" },
      { code: "FWC-10", name: "Uruguay 1950" },
      { code: "FWC-11", name: "West Germany 1954" },
      { code: "FWC-12", name: "Brazil 1962" },
      { code: "FWC-13", name: "West Germany 1974" },
      { code: "FWC-14", name: "Argentina 1986" },
      { code: "FWC-15", name: "Brazil 1994" },
      { code: "FWC-16", name: "Brazil 2002" },
      { code: "FWC-17", name: "Italy 2006" },
      { code: "FWC-18", name: "Germany 2014" },
      { code: "FWC-19", name: "Argentina 2022" },
    ],
  },
  {
    name: "Extra Stars",
    stickers: [
      { code: "E-1", name: "Lionel Messi (Argentina)" },
      { code: "E-2", name: "Jérémy Doku (Belgium)" },
      { code: "E-3", name: "Vinicius Júnior (Brazil)" },
      { code: "E-4", name: "Alphonso Davies (Canada)" },
      { code: "E-5", name: "Luis Díaz (Colombia)" },
      { code: "E-6", name: "Luka Modrić (Croatia)" },
      { code: "E-7", name: "Moisés Caicedo (Ecuador)" },
      { code: "E-8", name: "Mohamed Salah (Egypt)" },
      { code: "E-9", name: "Jude Bellingham (England)" },
      { code: "E-10", name: "Kylian Mbappé (France)" },
      { code: "E-11", name: "Florian Wirtz (Germany)" },
      { code: "E-12", name: "Raúl Jiménez (Mexico)" },
      { code: "E-13", name: "Achraf Hakimi (Morocco)" },
      { code: "E-14", name: "Cody Gakpo (Netherlands)" },
      { code: "E-15", name: "Erling Haaland (Norway)" },
      { code: "E-16", name: "Cristiano Ronaldo (Portugal)" },
      { code: "E-17", name: "Heung-min Son (South Korea)" },
      { code: "E-18", name: "Lamine Yamal (Spain)" },
      { code: "E-19", name: "Christian Pulisic (United States)" },
      { code: "E-20", name: "Federico Valverde (Uruguay)" },
    ],
  },
  {
    name: "Coca-Cola",
    stickers: [
      { code: "CC-1", name: "Lamine Yamal (Spain)" },
      { code: "CC-2", name: "Joshua Kimmich (Germany)" },
      { code: "CC-3", name: "Harry Kane (England)" },
      { code: "CC-4", name: "Santiago Giménez (Mexico)" },
      { code: "CC-5", name: "Josko Gvardiol (Croatia)" },
      { code: "CC-6", name: "Federico Valverde (Uruguay)" },
      { code: "CC-7", name: "Jefferson Lerma (Colombia)" },
      { code: "CC-8", name: "Enner Valencia (Ecuador)" },
      { code: "CC-9", name: "Gabriel Magalhães (Brazil)" },
      { code: "CC-10", name: "Virgil van Dijk (Netherlands)" },
      { code: "CC-11", name: "Alphonso Davies (Canada)" },
      { code: "CC-12", name: "Emiliano Martinez (Argentina)" },
      { code: "CC-13", name: "Raúl Jiménez (Mexico)" },
      { code: "CC-14", name: "Lautaro Martínez (Argentina)" },
    ],
  },
];
